# .gitlab-ci.yml
name: CI

on:
  push:
    branches:
      - main

jobs:
  build_and_push_images:
    stage: build
    variables:
      IMAGE_BACKEND: paschyz/taskify-back
      IMAGE_FRONTEND: paschyz/taskify-front
    services:
      - docker:19.03.12-dind
    before_script:
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    script:
      - cd back
      - docker build -t $IMAGE_BACKEND .
      - docker push $IMAGE_BACKEND
      - cd ../front
      - docker build -t $IMAGE_FRONTEND .
      - docker push $IMAGE_FRONTEND

  test:
    stage: test
    script:
      # Run your tests here
      - echo "Running tests..."

  deploy_backend:
    stage: deploy
    script:
      - cd back
      - docker-compose up -d

  deploy_frontend:
    stage: deploy
    script:
      - cd front
      - docker-compose up -d

# Optionally, you might want to add additional jobs for deployment steps, like deploying to Kubernetes or other environments.
